CREATE VIEW V_PRODUCTO_PRECIO
AS
SELECT 
    H.CODIGO,
    H.CODIGO_PRODUCTO,
    P.DESCRIPCION,
    H.PRECIO,
    H.FECHA,
    u.usuario,
    u.nombre AS NOMBRE_USUARIO
FROM 
    PRODUCTO P 
    INNER JOIN HISTORICO_PRECIO H ON P.CODIGO=H.CODIGO_PRODUCTO 
    INNER JOIN USUARIO U ON U.ID_USUARIO= H.ID_USUARIO
    AND P.ESTADO='1' AND H.ESTADO='1'
