create or replace PACKAGE PKG_PRODUCTO AS 

    PROCEDURE SP_LISTAR
    (
        P_CURSOR    OUT SYS_REFCURSOR,
        P_DESCRIPCION    IN  PRODUCTO.DESCRIPCION%TYPE
    );
    
    PROCEDURE SP_LISTAR_PRECIOS
    (
        P_CURSOR    OUT SYS_REFCURSOR,
        P_DESCRIPCION    IN  PRODUCTO.DESCRIPCION%TYPE
    );

    PROCEDURE SP_LISTAR_PRECIOS_X_CODIGO
    (
        P_CURSOR    OUT SYS_REFCURSOR,
        P_CODIGO    IN  PRODUCTO.CODIGO%TYPE
    );
    
   PROCEDURE SP_BUSCAR_X_ID
    (
        P_CURSOR    OUT SYS_REFCURSOR,
        P_CODIGO    IN  PRODUCTO.CODIGO%TYPE
    );

    PROCEDURE SP_INSERTAR
    (
        P_CODIGO        OUT PRODUCTO.CODIGO%TYPE,
        P_SERIE         IN  PRODUCTO.SERIE%TYPE,
        P_DESCRIPCION   IN  PRODUCTO.DESCRIPCION%TYPE,
        P_PRECIO        IN  PRODUCTO.PRECIO%TYPE,
        P_MARCA         IN  PRODUCTO.MARCA%TYPE,
        P_MODELO        IN  PRODUCTO.MODELO%TYPE,
        -- Auditoria
        P_AUD_IDUSUARIO IN  PRODUCTO.AUD_IDUSUARIO%TYPE,
        P_AUD_SESION    IN  PRODUCTO.AUD_SESION%TYPE,
        P_AUD_IP        IN  PRODUCTO.AUD_IP%TYPE
    );

    PROCEDURE SP_ACTUALIZAR
    (
        P_CODIGO        OUT PRODUCTO.CODIGO%TYPE,
        P_SERIE         IN  PRODUCTO.SERIE%TYPE,
        P_DESCRIPCION   IN  PRODUCTO.DESCRIPCION%TYPE,
        P_PRECIO        IN  PRODUCTO.PRECIO%TYPE,
        P_MARCA         IN  PRODUCTO.MARCA%TYPE,
        P_MODELO        IN  PRODUCTO.MODELO%TYPE,
        -- Auditoria
        P_AUD_IDUSUARIO IN  PRODUCTO.AUD_IDUSUARIO%TYPE,
        P_AUD_SESION    IN  PRODUCTO.AUD_SESION%TYPE,
        P_AUD_IP        IN  PRODUCTO.AUD_IP%TYPE
    );

    PROCEDURE SP_ELIMINAR
    (
        P_CODIGO        IN  PRODUCTO.CODIGO%TYPE,
        -- Auditoria
        P_AUD_IDUSUARIO IN  PRODUCTO.AUD_IDUSUARIO%TYPE,
        P_AUD_SESION    IN  PRODUCTO.AUD_SESION%TYPE,
        P_AUD_IP        IN  PRODUCTO.AUD_IP%TYPE
    );

END PKG_PRODUCTO;
